# From: https://github.com/marketplace/actions/compile-arduino-sketches
# Uses: https://github.com/arduino/compile-sketches
name: Arduino Compile Sketches

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  compile-sketches: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Clone compile-sketches to get python version (using nektos/act locally)
        if: ${{ env.ACT }}
        run: cd /tmp; git clone 'https://github.com/arduino/compile-sketches'
      - name: setup-python (when running locally for nektos/act compatibility)
        if: ${{ env.ACT }}
        uses: actions/setup-python@v4
        with:
          python-version-file: /tmp/compile-sketches/.python-version
      - name: Install Poetry (when running locally for nektos/act compatibility)
        if: ${{ env.ACT }}
        uses: snok/install-poetry@v1
      - name: Install pipx (when running locally for nektos/act compatibility)
        if: ${{ env.ACT }}
        run: pip install pipx
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'energia:msp430:MSP-EXP430G2553LP'
          platforms: |
            - name: 'energia:msp430'
              version: latest
              source-url: 'https://raw.githubusercontent.com/Andy4495/TI_Platform_Cores_For_Arduino/main/json/package_energia_minimal_MSP_107_index.json'
          sketch-paths: |
            - .
          verbose: true
          enable-warnings-report: true
          libraries: |
            - source-path: ./
            - source-url: https://github.com/Andy4495/MspTandV.git
            - source-url: https://github.com/Andy4495/SWI2C.git
            - source-url: https://github.com/Andy4495/Weather_Sensors_SWI2C.git
      - name: Print the job summary
        if: ${{ inputs.message }}
        run: |
          echo ${{ inputs.message }} >$GITHUB_STEP_SUMMARY
